[project]
name = "skills"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pymysql>=1.1.2",
    "sqlalchemy>=2.0.44",
    "pyodbc>=5.0.0", # MSSQL 연결을 위한 드라이버
    "ipykernel>=7.1.0",
]
